AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud infrastructure for Payroll System'

Parameters:
  DBUsername:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true
  FrontendImageUri:
    Type: String
  BackendImageUri:
    Type: String
  SecurityGroupId:
    Type: String
    Default: sg-05da441b7af99668b
    Description: Existing Security Group ID with MySQL port 3306 open

Resources:
  # IAM Role for App Runner to pull from ECR
  AppRunnerECRAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # RDS MySQL Database
  PayrollDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: payroll_db
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref SecurityGroupId

  # App Runner for Backend
  BackendService:
    Type: 'AWS::AppRunner::Service'
    Properties:
      ServiceName: payroll-backend
      NetworkConfiguration:
        IpAddressType: IPV4
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Ref BackendImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '3000'
            RuntimeEnvironmentVariables:
              - Name: DB_HOST
                Value: !GetAtt PayrollDatabase.Endpoint.Address
              - Name: DB_USER
                Value: !Ref DBUsername
              - Name: DB_PASSWORD
                Value: !Ref DBPassword
              - Name: DB_NAME
                Value: payroll_db
              - Name: JWT_SECRET
                Value: 'your_production_jwt_secret'

  # App Runner for Frontend
  FrontendService:
    Type: 'AWS::AppRunner::Service'
    Properties:
      ServiceName: payroll-frontend
      NetworkConfiguration:
        IpAddressType: IPV4
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Ref FrontendImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '80'

Outputs:
  DatabaseEndpoint:
    Value: !GetAtt PayrollDatabase.Endpoint.Address
  BackendUrl:
    Value: !GetAtt BackendService.ServiceUrl
  FrontendUrl:
    Value: !GetAtt FrontendService.ServiceUrl
